#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "dawarich"
name = "Dawarich"
description.en = "Self-hostable alternative to Google Timeline "

version = "1.8.1~ynh1"

maintainers = ["Thovi98"]

[upstream]

license = "AGPL-3.0"
website = "https://dawarich.app/"
admindoc = "https://dawarich.app/docs/intro"
code = "https://github.com/Freika/dawarich"

fund = "https://www.patreon.com/freika"

[integration]
yunohost = ">= 13.0"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"
    help.en = "You will have to login with the email of this user and the password you’ll set below."
    help.fr = "Vous devrez vous connecter avec l’adresse courriel de cet utilisateur et le mot de passe configuré ci-dessous."

    [install.password]
    help.en = "Choose a password for your admin user."
    help.fr = "Choisissez un mot de passe pour l’utilisateur admin."
    type = "password"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/Freika/dawarich/archive/refs/tags/1.8.1.tar.gz"
    sha256 = "b7fa61b8228d430fd8c7bfd501ce1259897cae657446006f2375d9cfba466406"
    
    autoupdate.strategy = "latest_github_release"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 3000
    
    [resources.apt]
    packages = [
    # Ruby
    "build-essential", "gcc", "g++", "autoconf", "bison", "make",
    "libssl-dev", "libyaml-dev", "libreadline6-dev", "zlib1g-dev",
    "libncurses5-dev", "libffi-dev", "libgdbm-dev", "libgdbm6",
    "libjemalloc-dev", "pkg-config",

    # gems Ruby
    "libxml2-dev", "libxslt1-dev",    
    "libpq-dev",                      
    "libicu-dev",                    
    "libidn11-dev",                  
    "protobuf-compiler", "libprotobuf-dev", 
    "cmake",

    # Posqgresql & db
    "postgresql", "postgresql-contrib", "postgresql-postgis",
    "redis-server", "redis-tools",
]

    [resources.db]
    type = "psql"

    [resources.nodejs]
    version = "18.17.1"

    [resources.ruby]
    version = "3.4.6"
