#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

admin=$(ynh_user_get_info --username=$admin --key=username)
admin_mail=$(ynh_user_get_info --username=$admin --key=mail)

key=$(ynh_string_random --length=45 | base64)
ynh_app_setting_set --key=key --value=$key

secret_key_base=$(ynh_string_random --length=45 | base64)
ynh_app_setting_set --key=ksecret_key_base --value=$secret_key_base

redis_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --key=redis_db --value=$redis_db

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chown -R "$app:www-data" "$install_dir"

#=================================================
# PREPARE A POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Configuring the PostgreSQL database..."

# After the config files are added, before any DB operations:
ynh_psql_db_shell <<< "ALTER DATABASE template1 REFRESH COLLATION VERSION;" 2>/dev/null || true
ynh_psql_db_shell <<< "ALTER DATABASE postgres REFRESH COLLATION VERSION;" 2>/dev/null || true

#Create postgis extension
ynh_psql_db_shell <<< "ALTER USER $db_user WITH SUPERUSER;"
ynh_psql_db_shell <<< "CREATE EXTENSION IF NOT EXISTS postgis;"
ynh_psql_db_shell <<< "ALTER USER $db_user WITH NOSUPERUSER;"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

chmod 400 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building $app..."

pushd "$install_dir"
    env corepack enable
    ynh_hide_warnings ynh_exec_as_app yarn install --immutable
    gem update --system --no-document
	gem install bundler --no-document
    ynh_exec_as_app LD_PRELOAD=libjemalloc.so bundle config set --local path 'vendor/bundle'
    ynh_exec_as_app LD_PRELOAD=libjemalloc.so bundle config set --local without 'development test'
    ynh_exec_as_app LD_PRELOAD=libjemalloc.so bundle install --jobs 4 --retry 3

    set -o allexport
    source "$install_dir/.env"
    set +o allexport

    ynh_hide_warnings ynh_exec_as_app env $(cat $install_dir/.env | xargs) LD_PRELOAD=libjemalloc.so bundle exec $install_dir/bin/rails credentials:edit 

    ynh_hide_warnings ynh_exec_as_app env $(cat $install_dir/.env | xargs) LD_PRELOAD=libjemalloc.so bundle exec rails db:migrate
    ynh_exec_as_app env $(cat $install_dir/.env | xargs) LD_PRELOAD=libjemalloc.so bundle exec rails dawarich:backfill_place_names
    ynh_exec_as_app env $(cat $install_dir/.env | xargs) LD_PRELOAD=libjemalloc.so bundle exec rails dawarich:cleanup_suggested_places
    ynh_hide_warnings ynh_exec_as_app env $(cat $install_dir/.env | xargs) LD_PRELOAD=libjemalloc.so bundle exec rake data:migrate
    ynh_hide_warnings ynh_exec_as_app env $(cat $install_dir/.env | xargs) LD_PRELOAD=libjemalloc.so bundle exec rails db:seed
    ynh_hide_warnings ynh_exec_as_app env $(cat $install_dir/.env | xargs) LD_PRELOAD=libjemalloc.so bundle exec rake assets:precompile

    ynh_safe_rm vendor/bundle/ruby/$ruby_version/cache/*.gem
popd 

ynh_script_progression "Creating user..."

#Create new admin user and delete default one
pushd "$install_dir"
    ynh_hide_warnings ynh_exec_as_app env $(cat $install_dir/.env | xargs) LD_PRELOAD=libjemalloc.so bundle exec rails runner "User.create!(email: '$admin_mail', password: '$password', admin: true)"
    ynh_hide_warnings ynh_exec_as_app env $(cat $install_dir/.env | xargs) LD_PRELOAD=libjemalloc.so bundle exec rails runner "User.find_by(email: 'demo@dawarich.app').destroy"
popd

#Remove unneeded files
ynh_safe_rm "$install_dir"/.cache
ynh_safe_rm "$install_dir"/node_modules
ynh_safe_rm "$install_dir"/.github
ynh_safe_rm "$install_dir"/.devcontainer
ynh_safe_rm "$install_dir"/.circleci
ynh_safe_rm "$install_dir"/docs
ynh_safe_rm "$install_dir"/test
ynh_safe_rm "$install_dir"/spec
ynh_safe_rm "$install_dir"/screenshots

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Use logrotate to manage application logfiles
ynh_config_add_logrotate
mkdir -p /var/log/$app
touch /var/log/$app/$app.log
touch /var/log/$app/$app-sidekig.log
chown $app:$app /var/log/$app

ynh_config_add_nginx

ynh_config_add_systemd --service="${app}" --template="dawarich.service"
ynh_config_add_systemd --service="${app}-sidekiq" --template="dawarich-sidekiq.service"

yunohost service add "$app" --description="$app’s service" --log="/var/log/$app/$app.log"
yunohost service add "$app-sidekiq" --description="$app sidekiq service" --log="/var/log/$app/$app-sidekiq.log"

# Create a dedicated Fail2Ban config
#ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path=/var/log/$app/$app.log --wait_until="Listening on"
ynh_systemctl --service=${app}-sidekiq --action="start" --log_path=/var/log/$app/$app-sidekiq.log --wait_until="Firing startup event"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
