#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"
ynh_systemctl --service="$app-sidekiq" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" 

chown -R "$app:www-data" "$install_dir"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

chmod 400 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building $app..."

pushd "$install_dir"
    env corepack enable
    ynh_hide_warnings ynh_exec_as_app yarn install --immutable
    gem update --system --no-document
	gem install bundler --no-document
    ynh_exec_as_app LD_PRELOAD=libjemalloc.so bundle config set --local path 'vendor/bundle'
    ynh_exec_as_app LD_PRELOAD=libjemalloc.so bundle config set --local without 'development test'
    ynh_exec_as_app LD_PRELOAD=libjemalloc.so bundle install --jobs 4 --retry 3

    set -o allexport
    source "$install_dir/.env"
    set +o allexport

    ynh_hide_warnings ynh_exec_as_app env $(cat $install_dir/.env | xargs) LD_PRELOAD=libjemalloc.so bundle exec $install_dir/bin/rails credentials:edit 

    ynh_hide_warnings ynh_exec_as_app env $(cat $install_dir/.env | xargs) LD_PRELOAD=libjemalloc.so bundle exec rails db:migrate
    ynh_hide_warnings ynh_exec_as_app env $(cat $install_dir/.env | xargs) LD_PRELOAD=libjemalloc.so bundle exec rake data:migrate
    #ynh_hide_warnings ynh_exec_as_app env $(cat $install_dir/.env | xargs) LD_PRELOAD=libjemalloc.so bundle exec rails db:seed
    ynh_hide_warnings ynh_exec_as_app env $(cat $install_dir/.env | xargs) LD_PRELOAD=libjemalloc.so bundle exec rake assets:precompile

    ynh_safe_rm vendor/bundle/ruby/$ruby_version/cache/*.gem
popd

#Remove unneeded files
ynh_safe_rm "$install_dir"/.cache
ynh_safe_rm "$install_dir"/node_modules
ynh_safe_rm "$install_dir"/.github
ynh_safe_rm "$install_dir"/.devcontainer
ynh_safe_rm "$install_dir"/.circleci
ynh_safe_rm "$install_dir"/docs
ynh_safe_rm "$install_dir"/test
ynh_safe_rm "$install_dir"/spec
ynh_safe_rm "$install_dir"/screenshots

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="${app}" --template="dawarich.service"
ynh_config_add_systemd --service="${app}-sidekiq" --template="dawarich-sidekiq.service"

yunohost service add "$app" --description="$app’s service" --log="/var/log/$app/$app.log"
yunohost service add "$app-sidekiq" --description="$app sidekiq service" --log="/var/log/$app/$app-sidekiq.log"

ynh_config_add_logrotate

#ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path=/var/log/$app/$app.log --wait_until="Listening on"
ynh_systemctl --service=${app}-sidekiq --action="start" --log_path=/var/log/$app/$app-sidekiq.log --wait_until="Firing startup event"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
